# Generated by Django 6.0.3 on 2026-03-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=255, verbose_name='Descrição Curta')),
                ('description', models.TextField(verbose_name='Descrição Longa')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('lead_time_text', models.CharField(default='Produção em 3 a 5 dias úteis', max_length=100, verbose_name='Prazo Estimado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Cor')),
                ('hex_optional', models.CharField(blank=True, help_text='Ex: #FF0000', max_length=7, verbose_name='Código Hexadecimal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Cor Disponível',
                'verbose_name_plural': 'Cores Disponíveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Rótulo do Campo (ex: Tamanho)')),
                ('field_type', models.CharField(choices=[('text', 'Texto Simples'), ('number', 'Número'), ('select', 'Seleção (Dropdown)')], default='text', max_length=20, verbose_name='Tipo de Campo')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('options_json', models.TextField(blank=True, help_text="Se for 'Seleção', separe as opções por vírgula. Ex: P,M,G", verbose_name='Opções')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Campo Personalizado',
                'verbose_name_plural': 'Campos Personalizados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Imagem')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo (SEO)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['order'],
            },
        ),
    ]
