# Generated by Django 6.0.3 on 2026-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/colors/%Y/%m/%d', verbose_name='Imagem da Cor'),
        ),
    ]
