# Generated by Django 6.0.3 on 2026-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('delivery_option', models.CharField(blank=True, max_length=100, verbose_name='Forma de Entrega/Retirada')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('items_json', models.JSONField(default=dict, verbose_name='Itens do Pedido (Snapshot)')),
                ('total_estimated', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Estimado')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('enviado_whatsapp', 'Enviado pro WhatsApp'), ('cancelado', 'Cancelado')], default='draft', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Rascunho de Pedido',
                'verbose_name_plural': 'Rascunhos de Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
