# Generated by Django 6.0.3 on 2026-03-05 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraft',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de desconto'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='total_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total após desconto'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Desconto (%)')),
                ('valid_from', models.DateTimeField(verbose_name='Válido a partir de')),
                ('valid_to', models.DateTimeField(verbose_name='Válido até')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de usos (opcional)')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usos realizados')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='catalog.category', verbose_name='Categoria Alvo (opcional)')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='Cupom aplicado'),
        ),
    ]
