# Generated by Django 6.0.3 on 2026-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdraft_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraft',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
    ]
